#include "AVL.hpp"

int main() {
	AVL<int> tree;


	// tree.add('q');
	// tree.add('w');
	// tree.add('w');
	// tree.add('e');
	// tree.add('r');
	// tree.add('t');
	// tree.add('y');
	// tree.add('u');
	// tree.add('i');
 	// tree.add('o');
 	// tree.add('p');
 	// tree.add('a');
 	// tree.add('s');
 	// tree.add('s');
 	// tree.add('s');
 	// tree.add('s');
 	// tree.add('s');
 	// tree.add('s');
 	// tree.add('s');
 	// tree.add('s');
 	// tree.add('s');
 	// tree.add('s');

	// tree.add(1);
	// tree.add(2);
	// tree.add(3);
	// tree.add(4);
	// tree.add(5);
	// tree.add(5);
	// tree.add(4);
	// tree.add(3);
	// tree.add(2);
	// tree.add(1);
	// tree.add(6);
	// tree.add(7);
	// tree.add(8);
	// tree.add(9);
	tree.add(9);
	tree.print();
	tree.add(2);
	tree.print();
	tree.add(7);
	tree.print();
	tree.add(6);
	tree.print();
	tree.add(3);
	tree.print();
	tree.add(1);
	tree.print();
	tree.add(5);
	tree.print();
	tree.add(4);
	// tree.add('r');
	// tree.add('g');
	// tree.add('p');
	// tree.add('h');
	// tree.add('o');
	// tree.add('a');
	// tree.add('n');
	// tree.add('l');
	// tree.add('k');
	// tree.add('v');
	// tree.add('j');
	// tree.add('q');
	// tree.add('e');
	// tree.add('d');
	// tree.add('c');
	// tree.add('u');
	// tree.add('b');
	// tree.add('y');
	tree.print();

// tree.add('q');
// tree.print(tree.root, 0, tree.root->height(tree.root));
// std::cout << "\n" << std::endl;
// tree.add('w');
// tree.print(tree.root, 0, tree.root->height(tree.root));
// std::cout << "\n" << std::endl;
// tree.add('e');
// tree.print(tree.root, 0, tree.root->height(tree.root));
// std::cout << "\n" << std::endl;
// tree.add('r');
// tree.print(tree.root, 0, tree.root->height(tree.root));
// std::cout << "\n" << std::endl;
// tree.add('t');
// tree.print(tree.root, 0, tree.root->height(tree.root));
// std::cout << "\n" << std::endl;
// tree.add('y');
// tree.print(tree.root, 0, tree.root->height(tree.root));
// std::cout << "\n" << std::endl;
// tree.add('u');
// tree.print(tree.root, 0, tree.root->height(tree.root));
// std::cout << "\n" << std::endl;
// tree.add('i');
// tree.print(tree.root, 0, tree.root->height(tree.root));
// std::cout << "\n" << std::endl;
// tree.add('o');
// tree.print(tree.root, 0, tree.root->height(tree.root));
// std::cout << "\n" << std::endl;
// std::cout << "=>add p" << std::endl;
// tree.add('p');
// tree.print();
// std::cout << "\n" << std::endl;
// std::cout << std::endl;
// std::cout << tree.root->height(tree.root) << std::endl;
}

